if(EXISTS "/home/ectf/Desktop/projects/cpp-http-server/build-asan/core_tests[1]_tests.cmake")
  include("/home/ectf/Desktop/projects/cpp-http-server/build-asan/core_tests[1]_tests.cmake")
else()
  add_test(core_tests_NOT_BUILT core_tests_NOT_BUILT)
endif()
