name: CI
on: [push, pull, request]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update &&& sudo apt-get install -y ninja-build
      - run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug
      - run: cmake --build build
      - run: ctest --test-dir build --output-on-failure